Epochs:   0%|                                                                                                                                                   | 0/100 [00:00<?, ?it/s]/Users/aklywtx/opt/anaconda3/lib/python3.11/site-packages/torch/nn/modules/loss.py:128: UserWarning: Using a target size (torch.Size([64])) that is different to the input size (torch.Size([64, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)                                                                                                      | 0/79 [00:00<?, ?it/s]
                                                                                                                                                                                        /Users/aklywtx/opt/anaconda3/lib/python3.11/site-packages/torch/nn/modules/loss.py:128: UserWarning: Using a target size (torch.Size([58])) that is different to the input size (torch.Size([58, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)███████████████████████████████████████████████████████████████████████████████████████████▎ | 78/79 [00:15<00:00,  4.91it/s]
                                                                                                                                                                                        /Users/aklywtx/opt/anaconda3/lib/python3.11/site-packages/torch/nn/modules/loss.py:128: UserWarning: Using a target size (torch.Size([57])) that is different to the input size (torch.Size([57, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)                                                                                                                             
Epochs:  24%|█████████████████████████████████                                                                                                         | 24/100 [06:52<21:47, 17.20s/it]
Testing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  5.97it/s]

Early stopping triggered after 25 epochs

Test Results:
Average Loss: 0.2587
MSE: 0.0912
MAE: 0.2587
Traceback (most recent call last):
  File "/Users/aklywtx/Desktop/VLM_Bias_research/NN_pretrain/models/mlp_train.py", line 77, in <module>
    main()
  File "/Users/aklywtx/Desktop/VLM_Bias_research/NN_pretrain/models/mlp_train.py", line 72, in main
    trainer.test(test_loader)
  File "/Users/aklywtx/Desktop/VLM_Bias_research/NN_pretrain/models/utils.py", line 200, in test
    self._analyze_results(avg_loss, predictions, actual_values)
  File "/Users/aklywtx/Desktop/VLM_Bias_research/NN_pretrain/models/utils.py", line 228, in _analyze_results
    ax2.scatter(actual_values, predictions - actual_values, color="red", alpha=0.5)
  File "/Users/aklywtx/opt/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py", line 1476, in inner
    return func(
           ^^^^^
  File "/Users/aklywtx/opt/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 4787, in scatter
    raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size
